version: '3.9' 

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat-engine
    ports:
      - "5433:5432"  
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data:
